name: LocalFlow
options:
  bundleIdPrefix: com.localflow
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    version: 2.6.4

settings:
  base:
    PRODUCT_NAME: LocalFlow
    MARKETING_VERSION: "0.5.0"
    CURRENT_PROJECT_VERSION: "9"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    CODE_SIGN_STYLE: Manual
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: "-"
    ARCHS: arm64
    ONLY_ACTIVE_ARCH: NO

targets:
  LocalFlow:
    type: application
    platform: macOS
    sources:
      - path: LocalFlow
        excludes:
          - "**/.DS_Store"
    resources:
      - path: LocalFlow/Resources
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.localflow.app
        INFOPLIST_FILE: LocalFlow/Info.plist
        CODE_SIGN_ENTITLEMENTS: LocalFlow/LocalFlow.entitlements
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        HEADER_SEARCH_PATHS:
          - "$(PROJECT_DIR)/vendor/whisper.cpp/include"
          - "$(PROJECT_DIR)/vendor/whisper.cpp/ggml/include"
        LIBRARY_SEARCH_PATHS:
          - "$(PROJECT_DIR)/vendor/whisper.cpp/build/src"
          - "$(PROJECT_DIR)/vendor/whisper.cpp/build/ggml/src"
          - "$(PROJECT_DIR)/vendor/whisper.cpp/build/ggml/src/ggml-blas"
          - "$(PROJECT_DIR)/vendor/whisper.cpp/build/ggml/src/ggml-metal"
        SWIFT_OBJC_BRIDGING_HEADER: "$(PROJECT_DIR)/LocalFlow/LocalFlow-Bridging-Header.h"
        OTHER_LDFLAGS:
          - "-lwhisper"
          - "-lggml"
          - "-lggml-base"
          - "-lggml-cpu"
          - "-lggml-metal"
          - "-lggml-blas"
          - "-lc++"
        ENABLE_HARDENED_RUNTIME: NO
        LSUIElement: YES
    dependencies:
      - sdk: Metal.framework
      - sdk: MetalKit.framework
      - sdk: Accelerate.framework
      - sdk: CoreML.framework
      - sdk: AVFoundation.framework
      - sdk: Carbon.framework
      - sdk: ApplicationServices.framework
      - package: Sparkle
        product: Sparkle

schemes:
  LocalFlow:
    build:
      targets:
        LocalFlow: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
